package bloodon.ui;

import javax.swing.ButtonGroup;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author BlackPearl
 */
public class AddDonor extends javax.swing.JFrame {
    
    private SearchDonor searchDonor;
    /**
     * Creates new form Donordetails
     */
    public AddDonor(SearchDonor sd) {
        initComponents();
        gender = new ButtonGroup();
        gender.add(radioBtnMale);
        gender.add(radioBtnFemale);
        for (String bg : Constants.bloodGroups) {
            comboBloodGroup.addItem(bg);
        }
        this.searchDonor = sd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDonorName = new java.awt.Label();
        lblBloodGroup = new java.awt.Label();
        lblGender = new java.awt.Label();
        lblMobileNo = new java.awt.Label();
        txtDonorName = new java.awt.TextField();
        txtMobileNo = new java.awt.TextField();
        radioBtnMale = new javax.swing.JRadioButton();
        radioBtnFemale = new javax.swing.JRadioButton();
        btnSubmit = new javax.swing.JButton();
        comboBloodGroup = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Donor");
        setResizable(false);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setName("Add Donor"); // NOI18N

        lblDonorName.setText("Donor Name");

        lblBloodGroup.setText("Blood Group:");

        lblGender.setText("Gender:");

        lblMobileNo.setText("Mobile No.:");

        radioBtnMale.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        radioBtnMale.setText("Male");
        radioBtnMale.setName(""); // NOI18N

        radioBtnFemale.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        radioBtnFemale.setText("Female");

        btnSubmit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit(evt);
            }
        });

        comboBloodGroup.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDonorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBloodGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioBtnMale, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(radioBtnFemale))
                            .addComponent(txtDonorName, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDonorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonorName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboBloodGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lblBloodGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnMale)
                    .addComponent(radioBtnFemale)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMobileNo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lblMobileNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit
        String bloodGroup = (String) comboBloodGroup.getSelectedItem();        
        String donorName = txtDonorName.getText();
        String mobileNo = txtMobileNo.getText();
        String gender = "";
        if (radioBtnMale.isSelected()) {
            gender = "male";
        } else if (radioBtnFemale.isSelected()) {
            gender = "female";
        }
        if(donorName.isBlank()){
            JOptionPane.showMessageDialog(null,"Please enter donor name");
            return;
        }
        if(bloodGroup.isBlank()){
            JOptionPane.showMessageDialog(null,"Please select blood group");
            return;
        }
        if(gender.isBlank()){
            JOptionPane.showMessageDialog(null,"Please select gender");
            return;
        }
        if(mobileNo.isBlank()){
            JOptionPane.showMessageDialog(null,"Please enter mobile no");
            return;
        }
        try {
            Connection con=DB.getConnection();
            String query="INSERT INTO donor (name,blood_group,gender,mobile_no,created_at,updated_at)VALUES(?,?,?,?,NOW(),NOW())";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, donorName);
            pst.setString(2, bloodGroup);
            pst.setString(3,gender);
            pst.setString(4, mobileNo);
            pst.execute();
            JOptionPane.showMessageDialog(null, "donor added successfully");           
            con.close();
            this.searchDonor.loadData();
            this.dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(AddDonor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submit

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> comboBloodGroup;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label lblBloodGroup;
    private java.awt.Label lblDonorName;
    private java.awt.Label lblGender;
    private java.awt.Label lblMobileNo;
    private javax.swing.JRadioButton radioBtnFemale;
    private javax.swing.JRadioButton radioBtnMale;
    private java.awt.TextField txtDonorName;
    private java.awt.TextField txtMobileNo;
    // End of variables declaration//GEN-END:variables
    private ButtonGroup gender;
}
